plugins:
  - jekyll-gallery-generator

gallery:
  dir: galleries
  title: "Art"
  title_prefix: ""
  galleries:
    Paintings:
      name: "Paintings"
      best_image: SunSpots-cell-photo-562x800.jpg
    TreeCreatures:
      name: "TreeCreatures"
      best_image: Equibark_LauraGarabedian.jpg
    Inkwork:
      name: "Inkwork"
    Studies:
      name: "Studies"
      best_image: Memories-of-Africa-Lions-Gaze.jpg
