collections:
  front_gallery:
    output: true

plugins:
  - jekyll-gallery-generator

gallery:
  dir: galleries
  title: "Art"
  title_prefix: ""
  sort_field: "date_time"
  galleries:
    Paintings:
      name: "Paintings"
      best_image: paintings.jpg
      sort_reverse: true
    Inkwork:
      name: "Inkwork"
      best_image: inkwork.jpg
      sort_reverse: true
    Submissions:
      name: "Submissions"
      hidden: true
      sort_reverse: true
    TreeCreatures:
      name: "TreeCreatures"
      hidden: true
      sort_reverse: true

